<?php

namespace Api\Objects\Postman;

class ImportOperationCollectionBuilder extends OperationCollectionBuilder
{
	/**
	 * @return array|string[]
	 */
	protected function getOperationNames(): array
	{
		return [ 'batch', 'create', 'create-with-file', 'download-errors', 'read', 'query', 'update'];
	}

	/**
	 * @param $operationName
	 * @return bool
	 */
	public function canDoOperation($operationName): bool
	{
		switch ($operationName) {
			case 'batch':
			case 'create-with-file':
			case 'download-errors':
				return true;
			default:
				return parent::canDoOperation($operationName);
		}
	}

	/**
	 * @param string $operationName
	 * @return OperationBuilder
	 */
	public function getOperationBuilder(string $operationName): OperationBuilder
	{
		switch ($operationName) {
			case 'batch':
				return new ImportBatchOperationBuilder($this->objectDefinition, $this->version);
			case 'create-with-file':
				return new ImportCreateWithFileOperationBuilder($this->objectDefinition, $this->version);
			case 'download-errors':
				return new ImportDownloadErrorsOperationBuilder($this->objectDefinition, $this->version);
			case 'update':
				return new ImportUpdateOperationBuilder($this->objectDefinition, $this->version);
			default:
				return parent::getOperationBuilder($operationName); // TODO: Change the autogenerated stub
		}
	}
}
